const translations={
  en:{
    'nav.home':'Home','nav.house':'The house','nav.gallery':'Photos','nav.location':'Location','nav.about':'About us','nav.book':'Book now',
    'hero.eyebrow':'Kissimmee · Florida','hero.title':'Your Orlando home, close to everything.','hero.text':'Comfort for up to 8 guests, a private pool and Disney just minutes away.','hero.cta':'Check available dates','hero.photos':'Explore the house',
    'facts.guests':'guests','facts.bedrooms':'bedrooms','facts.bathrooms':'bathrooms','facts.disney':'from Disney',
    'booking.eyebrow':'Plan your stay','booking.title':'Choose your travel dates','booking.text':'Select check-in and check-out. We will confirm availability and send a quote by WhatsApp.','booking.checkin':'Check-in','booking.checkout':'Check-out','booking.quote':'Request a quote','booking.note':'Your booking will be confirmed after the host replies.',
    'calendar.available':'Available for inquiry','calendar.selected':'Selected','calendar.select':'Select',
    'house.eyebrow':'Bella Vida Resort','house.title':'Space, privacy and comfort for the whole family.','house.text':'A complete 4-bedroom home, designed for relaxing after the parks, cooking with ease and enjoying Orlando at your own pace.',
    'features.poolTitle':'Private pool','features.poolText':'Screened area and optional heating, so you can enjoy it any time of year.','features.kitchenTitle':'Full kitchen','features.kitchenText':'Cookware, appliances and a breakfast bar connected to the living and dining rooms.','features.resortTitle':'Resort amenities','features.resortText':'Clubhouse, pool, spa, gym, playground, courts and 24-hour security.','features.connectedTitle':'Everything connected','features.connectedText':'Wi-Fi, cable TV, central air conditioning and parking in front of the house.',
    'gallery.eyebrow':'See every detail','gallery.title':'A home made for great moments.','gallery.cta':'View all photos',
    'location.eyebrow':'A convenient location','location.title':'More time enjoying. Less time on the road.','location.text':'At Bella Vida Resort in Kissimmee, close to theme parks, outlets, supermarkets and restaurants.',
    'about.eyebrow':'Made by travelers, for travelers','about.title':'The Orlando experience with all the comfort of home.','about.text1':'We are a Brazilian couple who fell in love with Orlando. After many hotel stays, we realized we wanted more room, privacy and the freedom to enjoy the trip at our own pace.','about.text2':'That is why we prepared this Bella Vida Resort home to welcome families with care, safety and everything we would want on our own vacation.','about.cta':'Check the dates',
    'cta.eyebrow':'Your trip starts here','cta.title':'Ready to experience Orlando your way?','cta.button':'Check availability','footer.text':'Comfort, privacy and the perfect location for your Orlando vacation.','footer.links':'Links','footer.contact':'Contact'
  }
};

const state={lang:localStorage.getItem('orh-language')||'pt',view:new Date(new Date().getFullYear(),new Date().getMonth(),1),start:null,end:null};
const ptDefaults={};document.querySelectorAll('[data-i18n]').forEach(el=>ptDefaults[el.dataset.i18n]=el.textContent);

function t(key){return state.lang==='en'?(translations.en[key]||ptDefaults[key]||key):(ptDefaults[key]||key)}
function setLanguage(lang){state.lang=lang;localStorage.setItem('orh-language',lang);document.documentElement.lang=lang==='en'?'en-US':'pt-BR';document.querySelectorAll('[data-i18n]').forEach(el=>{el.textContent=t(el.dataset.i18n)});document.querySelector('#language-name').textContent=lang==='en'?'English':'Português';document.querySelector('#language-code').textContent=lang==='en'?'EN':'PT';document.querySelector('.language-button').setAttribute('aria-label',lang==='en'?'Choose language':'Escolher idioma');document.querySelectorAll('[data-language]').forEach(option=>{option.classList.toggle('is-active',option.dataset.language===lang);option.querySelector('i').textContent=option.dataset.language===lang?'✓':''});document.title=lang==='en'?'Orlando Rent Homes | Your home near Disney':'Orlando Rent Homes | Sua casa perto da Disney';renderCalendar();updateSelection()}

const languagePicker=document.querySelector('.language-picker');const languageButton=document.querySelector('.language-button');const languageMenu=document.querySelector('#language-menu');
function closeLanguageMenu(){languageMenu.hidden=true;languageButton.setAttribute('aria-expanded','false')}
languageButton.addEventListener('click',()=>{const willOpen=languageMenu.hidden;languageMenu.hidden=!willOpen;languageButton.setAttribute('aria-expanded',String(willOpen))});
document.querySelectorAll('[data-language]').forEach(option=>option.addEventListener('click',()=>{setLanguage(option.dataset.language);closeLanguageMenu()}));
document.addEventListener('click',event=>{if(!languagePicker.contains(event.target))closeLanguageMenu()});
document.addEventListener('keydown',event=>{if(event.key==='Escape')closeLanguageMenu()});

const menuButton=document.querySelector('.menu-button');const mobileNav=document.querySelector('#mobile-nav');menuButton.addEventListener('click',()=>{const open=menuButton.getAttribute('aria-expanded')==='true';menuButton.setAttribute('aria-expanded',String(!open));mobileNav.hidden=open});mobileNav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{mobileNav.hidden=true;menuButton.setAttribute('aria-expanded','false')}));

const dayNames={pt:['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'],en:['Sun','Mon','Tue','Wed','Thu','Fri','Sat']};
const calendar=document.querySelector('#calendar');
function startOfDay(date){return new Date(date.getFullYear(),date.getMonth(),date.getDate())}
function sameDay(a,b){return a&&b&&a.getFullYear()===b.getFullYear()&&a.getMonth()===b.getMonth()&&a.getDate()===b.getDate()}
function formatDate(date){return date?new Intl.DateTimeFormat(state.lang==='en'?'en-US':'pt-BR',{day:'2-digit',month:'short',year:'numeric'}).format(date):t('calendar.select')}
function renderCalendar(){calendar.innerHTML='';dayNames[state.lang].forEach(name=>{const el=document.createElement('div');el.className='calendar-day-name';el.textContent=name;calendar.appendChild(el)});const year=state.view.getFullYear(),month=state.view.getMonth(),first=new Date(year,month,1),days=new Date(year,month+1,0).getDate(),today=startOfDay(new Date());document.querySelector('#calendar-title').textContent=new Intl.DateTimeFormat(state.lang==='en'?'en-US':'pt-BR',{month:'long',year:'numeric'}).format(first);for(let i=0;i<first.getDay();i++){const blank=document.createElement('span');blank.className='calendar-blank';calendar.appendChild(blank)}for(let day=1;day<=days;day++){const date=new Date(year,month,day);const button=document.createElement('button');button.type='button';button.className='calendar-day';button.textContent=day;button.disabled=date<today;button.setAttribute('aria-label',formatDate(date));if(sameDay(date,today))button.classList.add('is-today');if(sameDay(date,state.start))button.classList.add('is-start');if(sameDay(date,state.end))button.classList.add('is-end');if(state.start&&state.end&&date>state.start&&date<state.end)button.classList.add('is-range');button.addEventListener('click',()=>selectDate(date));calendar.appendChild(button)}}
function selectDate(date){if(!state.start||(state.start&&state.end)||date<=state.start){state.start=date;state.end=null}else{state.end=date}updateSelection();renderCalendar()}
function updateSelection(){document.querySelector('#checkin-label').textContent=state.start?formatDate(state.start):t('calendar.select');document.querySelector('#checkout-label').textContent=state.end?formatDate(state.end):t('calendar.select');document.querySelector('#quote-button').disabled=!(state.start&&state.end)}
document.querySelector('#calendar-prev').addEventListener('click',()=>{const now=new Date();const prev=new Date(state.view.getFullYear(),state.view.getMonth()-1,1);if(prev>=new Date(now.getFullYear(),now.getMonth(),1)){state.view=prev;renderCalendar()}});document.querySelector('#calendar-next').addEventListener('click',()=>{state.view=new Date(state.view.getFullYear(),state.view.getMonth()+1,1);renderCalendar()});
document.querySelector('#quote-button').addEventListener('click',()=>{const message=state.lang==='en'?`Hello! I would like a quote for Orlando Rent Homes. Check-in: ${formatDate(state.start)}. Check-out: ${formatDate(state.end)}.`:`Olá! Gostaria de um orçamento para a Orlando Rent Homes. Entrada: ${formatDate(state.start)}. Saída: ${formatDate(state.end)}.`;window.open(`https://wa.me/5511999066659?text=${encodeURIComponent(message)}`,'_blank','noopener')});

const gallery=[...document.querySelectorAll('.gallery-item')];const lightbox=document.querySelector('#lightbox');const lightboxImage=document.querySelector('#lightbox-image');let activeImage=0;function openImage(index){activeImage=index;lightboxImage.src=gallery[index].dataset.full;lightbox.showModal()}gallery.forEach((item,index)=>item.addEventListener('click',()=>openImage(index)));document.querySelector('#show-all').addEventListener('click',()=>openImage(0));document.querySelector('.lightbox-close').addEventListener('click',()=>lightbox.close());document.querySelector('.lightbox-prev').addEventListener('click',()=>openImage((activeImage-1+gallery.length)%gallery.length));document.querySelector('.lightbox-next').addEventListener('click',()=>openImage((activeImage+1)%gallery.length));lightbox.addEventListener('click',e=>{if(e.target===lightbox)lightbox.close()});

const revealTargets=document.querySelectorAll('.booking-copy,.calendar-card,.intro-grid>*,.feature-grid article,.section-heading,.gallery-item,.location-card,.location-grid>img,.about-grid>*,.cta-inner>*');
revealTargets.forEach((element,index)=>{element.classList.add('reveal');element.style.setProperty('--reveal-delay',`${Math.min(index%5,4)*70}ms`)});
if('IntersectionObserver'in window){const revealObserver=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');revealObserver.unobserve(entry.target)}})},{threshold:.13,rootMargin:'0px 0px -40px'});revealTargets.forEach(element=>revealObserver.observe(element))}else{revealTargets.forEach(element=>element.classList.add('is-visible'))}

document.querySelector('#year').textContent=new Date().getFullYear();setLanguage(state.lang);
